grep -r -i  ' : jmp qword ptr \[rsi + 0x3c\]$'
grep -r -i  ' : jmp qword ptr \[rsi + 0x3d\]$'
grep -r -i  ' : jmp qword ptr \[rsi + 0x3e\]$'
grep -r -i  ' : push rbp ; jmp qword ptr \[rsi\]$'
grep -r -i  ' : pop rbx ; pop r14 ; pop rbp ; jmp qword ptr \[rsi + 0x10\]$'
grep -r -i  ' : lea rsp, \[rsi + 0x20\] ; repz ret$'
grep -r -i  ' : add rsp, 0x28 ; pop rbp ; ret$'
grep -r -i  ' : add rsp, 0xb0 ; pop rbp ; ret$'
grep -r -i  ' : ret$'
grep -r -i  ' : pop rdi ; ret$'
grep -r -i  ' : pop rsi ; ret$'
grep -r -i  ' : pop rdx ; ret$'
grep -r -i  ' : pop rcx ; ret$'
grep -r -i  ' : pop r8 ; pop rbp ; ret$'
grep -r -i  ' : pop r12 ; ret$'
grep -r -i  ' : pop rax ; ret$'
grep -r -i  ' : pop rbp ; ret$'
grep -r -i  ' : push rsp ; pop rsi ; ret$'
grep -r -i  ' : mov rdi, qword ptr \[rdi\] ; pop rbp ; jmp rax$'
grep -r -i  ' : mov byte ptr \[rcx\], al ; ret$'
grep -r -i  ' : mov rdi, rbx ; call r12$'
grep -r -i  ' : mov rdi, r14 ; call r12$'
grep -r -i  ' : mov rsi, rbx ; call rax$'
grep -r -i  ' : mov r14, rax ; call r8$'
grep -r -i  ' : add rdi, rcx ; ret$'
grep -r -i  ' : sub rsi, rdx ; mov rax, rsi ; pop rbp ; ret$'
grep -r -i  ' : jmp r14$'